### ISSUE TITLE
숙련 주차 개인과제 피드백 - 정영훈 튜터

### ISSUE THREAD

**Issue by jyh7a** [soobeen0301/recruitment-site#23]
숙련주차 과제 수고 많으셨습니다. 

깃 커밋 메세지도 잘 작성해 주셨습니다. 
README는 프로젝트 소개, api 링크, erd링크 등을 조금 더 추가해 주세요.

아래는 프로젝트 피드백입니다.

---

###  1. schema 수정
1.1. 스키마 파일을 보면 다른 모델들은 id 표현시 
resumeId, userInfoId 등으로 표현하는데 Users모델만 id로 표현하고 있습니다. 
`통일성 있게 user id도 userId로 변경 하는게 좋습니다.`
https://github.com/soobeen0301/recruitment-site/blob/4e2d40f7bf8fb8d7fb2bf7b2e2f77e8f4a3ee0ad/prisma/schema.prisma#L16-L17

<br/>

1.2. 이력서 상태 데이터 타입을 String도 좋지만 enum을 사용해서 해당 값에 있는 데이터만 받을 수 있도록 설정하면 
다른 값이 들어오는 오류를 방지할 수 있습니다.
https://github.com/soobeen0301/recruitment-site/blob/4e2d40f7bf8fb8d7fb2bf7b2e2f77e8f4a3ee0ad/prisma/schema.prisma#L34

예)

```javascript
enum ResumeStatus {
  APPLY
  DROP
  PASS
  INTERVIEW1
  INTERVIEW2
  FINAL_PASS
}

model Resumes {
  resumeId     Int      @id @default(autoincrement()) @map("resumeId")
  userId       Int      @map("userId") // Users 테이블을 참조하는 외래키
  title        String   @map("title")
  introduction String   @map("introduction") @db.Text
  status       ResumeStatus   @default("APPLY") @map("status")
  createdAt    DateTime @default(now()) @map("createdAt")
  updatedAt    DateTime @updatedAt @map("updatedAt")

  // Users 테이블과 관계를 설정합니다.
  user Users @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("Resumes")
}

```

<br/>

---

<br/>

###  2.  이력서 수정 라우터 PATCH로 변경
https://github.com/soobeen0301/recruitment-site/blob/4e2d40f7bf8fb8d7fb2bf7b2e2f77e8f4a3ee0ad/src/routers/resumes.router.js#L98-L100
현재 이력서 수정 라우터 잘 작성 되었습니다. 
이제는 PATCH 메서드로 변경 사항만 변경하도록 작성해보세요.

예)
```javascript
// 유효성 검사
    if (!title && !introduction) {
      return res.status(400).json({ message: '수정 할 정보를 입력해 주세요.' });
    }

    const resume = await prisma.resumes.findFirst({
      where: { resumeId, userId },
    });

    if (!resume) {
      return res.status(404).json({ message: '이력서가 존재하지 않습니다.' });
    }

    // 수정할 데이터 객체 생성
    const updateData = {};
    if (title) updateData.title = title;
    if (introduction) updateData.introduction = introduction;

    // 이력서 수정
    const resumeUpdate = await prisma.resumes.update({
      where: { resumeId },
      data: updateData,
    });
```

<br/>

---

<br/>

###  3.  에러 처리는 에러 미들웨어에서 하도록 변경
https://github.com/soobeen0301/recruitment-site/blob/4e2d40f7bf8fb8d7fb2bf7b2e2f77e8f4a3ee0ad/src/middlewares/auth.middleware.js#L35-L37
에러 처리 미들웨어를 잘 만들었으니 
모든 에러는 에러 처리 미들웨어 에서 관리하도록 수정해 주세요.

<br/>

---

<br/>

###  4.  추가 기능 구현
기본적인 회원가입 이력서 작성은 매우 잘 구현 하였습니다.
이제 refreshToken사용, role 추가, 이력서 로그 관리 등의 남은기능을 
하나씩 구현해 보시면 되겠습니다. 
구현하시면서 어렵거나 모르는 점은 동료분들 그리고 튜터님에게 질문주세요.

**Comment by soobeen0301** [comment]
추가 기능 구현 및 코드 리팩토링 완료
